---
title: Preterm prelabor rupture of membranes (PPROM)
date: 2025-12-11
---

## Diagnosis

- History of watery vaginal discharge.
- Sterile speculum examination demonstrating liquor.
- The role of ultrasound assessment of amniotic fluid volume is unclear.
- Digital vaginal exam should not be done unless in labor.
- 

## Investigations

- 

## Management

- Admission. Outpatient management only by consultant decision (individualized).
- Antibiotics:
    - Penicillin
    - Azithromycin
- Antenatal corticosteroids if <34/<36 weeks (dexamethasone, after screening for GDM):
    - 6 mg IM q12h x 4 doses, or
    - 12 mg IM q24h x 2 doses
- Magnesium sulfate for neuroprotection if <30/<34 weeks 
- Neonatologists should be informed when delivery is anticipated



## Special considerations

### Previable ROM

- <20 weeks → counsel regarding poor prognosis; risk of pulmonary hypoplasia, skeletal deformities, and neonatal death, in addition to risk of maternal morbidity from chorioamnionitis and sepsis.
- 20-<24 weeks → expectant management or termination of pregnancy after counseling. 
- 24 weeks → expectant management.

### Women with cerclage

- 

### Preterm labor

- Tocolysis: 

### Chorioamnionitis

- A combination of clinical assessment, maternal blood tests (CRP and WBC) and FHR should be used to diagnose chorioamnionitis in women with PPROM; these parameters should not be used in isolation
- Diagnosis:
    - Maternal fever >38°C plus 2 of the following:
        - Maternal tachycardia >100 bpm
        - Fetal tachycardia >160 bpm
        - Uterine tenderness
        - Foul smelling vaginal discharge
        - Elevated WBC >15,000/mm^3^ (less reliable if corticosteroids given)
- Management:
    - 

## Postpartum/preconceptional advice

- Risk in subsequent pregnancies is increased

## References

- RCOG 2021
- 
